# Generated by Django 5.1.6 on 2025-02-26 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('post_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=200)),
                ('image_url', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('cars', 'cars')], max_length=50)),
                ('condition', models.CharField(max_length=10)),
                ('sold', models.CharField(max_length=10)),
                ('sold_price', models.IntegerField()),
            ],
        ),
    ]
