# Generated by Django 5.1.6 on 2025-02-26 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_items_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='sold_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
