# Generated by Django 5.1.6 on 2025-02-26 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_item_condition_alter_item_sold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.TextField(default='def', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
