# Generated by Django 5.1.6 on 2025-02-26 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_title_alter_item_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='sold',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sold_price',
        ),
    ]
