# Generated by Django 5.1.6 on 2025-02-26 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_item_sold_remove_item_sold_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='item',
            new_name='active',
        ),
    ]
