# Generated by Django 5.1.6 on 2025-02-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_item_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name': 'active', 'verbose_name_plural': 'active'},
        ),
    ]
