# Generated by Django 5.1.6 on 2025-02-26 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_active_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='sold',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('post_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=200)),
                ('image_url', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('Cars', 'Cars'), ('Jewelry', 'Jewelry'), ('Clothing', 'Clothing')], max_length=50)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
                ('sold', models.CharField(max_length=50)),
                ('sold_date', models.DateField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'sold',
            },
        ),
        migrations.AlterModelOptions(
            name='active',
            options={'verbose_name_plural': 'active'},
        ),
    ]
