# Generated by Django 5.1.6 on 2025-02-26 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sold_alter_active_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='listing_type',
            field=models.CharField(default='Active', editable=False, max_length=10),
        ),
    ]
