# Generated by Django 5.1.6 on 2025-02-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_active_listing_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='listing_type',
            field=models.CharField(default='Active', editable=False, max_length=10),
        ),
    ]
