# Generated by Django 5.1.6 on 2025-02-26 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_active_listing_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='listing_type',
        ),
    ]
