# Generated by Django 5.1.6 on 2025-02-26 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_active_listing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='draft',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('post_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=200)),
                ('image_url', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('Cars', 'Cars'), ('Jewelry', 'Jewelry'), ('Clothing', 'Clothing')], max_length=50)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
                ('listing_type', models.CharField(default='Draft', editable=False, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'draft',
            },
        ),
        migrations.AlterModelOptions(
            name='sold',
            options={'verbose_name_plural': 'active'},
        ),
        migrations.AddField(
            model_name='sold',
            name='listing_type',
            field=models.CharField(default='Sold', editable=False, max_length=10),
        ),
    ]
