# Generated by Django 5.1.6 on 2025-02-26 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_draft_alter_sold_options_sold_listing_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sold',
            options={'verbose_name_plural': 'sold'},
        ),
    ]
