# Generated by Django 5.1.6 on 2025-02-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_sold_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sold',
            name='sold',
        ),
        migrations.AddField(
            model_name='sold',
            name='sell_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
