# Generated by Django 5.1.6 on 2025-02-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_sold_sold_sold_sell_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='active',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draft',
            name='quantity',
            field=models.IntegerField(default='0'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sold',
            name='quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
