# Generated by Django 5.1.6 on 2025-02-28 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_active_quantity_draft_quantity_sold_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='deleted',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=50)),
                ('title', models.TextField(max_length=50)),
                ('price', models.IntegerField()),
                ('post_date', models.DateField(auto_now=True)),
                ('description', models.TextField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('image_url', models.TextField(max_length=200)),
                ('category', models.CharField(choices=[('Cars', 'Cars'), ('Jewelry', 'Jewelry'), ('Clothing', 'Clothing')], max_length=50)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
                ('listing_type', models.CharField(default='Draft', editable=False, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'deleted',
            },
        ),
    ]
