# Generated by Django 5.1.6 on 2025-03-19 01:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_maubay_users_alter_active_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maubay_users',
            options={'verbose_name_plural': 'maubay_users'},
        ),
        migrations.AlterField(
            model_name='maubay_users',
            name='account_created',
            field=models.DateField(blank=True, default=datetime.date(2025, 3, 18)),
        ),
        migrations.AlterField(
            model_name='maubay_users',
            name='firstname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maubay_users',
            name='lastname',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='maubay_users',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
