# Generated by Django 5.1.6 on 2025-03-19 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_maubay_users_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maubay_users',
            name='account_created',
            field=models.DateField(default=datetime.date(2025, 3, 18)),
        ),
    ]
