# Generated by Django 5.1.6 on 2025-03-19 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_maubay_users_account_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maubay_users',
            name='account_created',
            field=models.DateField(auto_now=True),
        ),
    ]
