# Generated by Django 5.1.6 on 2025-03-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_maubay_users_account_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='maubay_users',
            name='email',
            field=models.CharField(default='none', max_length=100),
            preserve_default=False,
        ),
    ]
