# Generated by Django 5.1.6 on 2025-03-23 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_maubay_users_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='active',
            name='quantity',
        ),
    ]
