# Generated by Django 5.1.6 on 2025-03-23 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_remove_active_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deleted',
            options={'verbose_name_plural': 'active'},
        ),
        migrations.AlterModelOptions(
            name='draft',
            options={'verbose_name_plural': 'active'},
        ),
        migrations.AlterModelOptions(
            name='sold',
            options={'verbose_name_plural': 'active'},
        ),
        migrations.RemoveField(
            model_name='active',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='deleted',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='deleted',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='draft',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='listing_type',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='sell_price',
        ),
        migrations.RemoveField(
            model_name='sold',
            name='sold_date',
        ),
    ]
