# Generated by Django 5.1.6 on 2025-03-23 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_deleted_options_alter_draft_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='image_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
