# Generated by Django 5.1.6 on 2025-03-23 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_alter_sold_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='image_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='image_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
        migrations.AlterField(
            model_name='draft',
            name='image_url',
            field=models.ImageField(max_length=200, upload_to=''),
        ),
    ]
