# Generated by Django 5.1.6 on 2025-03-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_alter_active_image_url_alter_deleted_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='image_url',
            field=models.ImageField(upload_to='holder'),
        ),
    ]
