# Generated by Django 5.1.6 on 2025-03-23 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_deleted_image_url_alter_draft_image_url_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deleted',
            options={'verbose_name_plural': 'deleted'},
        ),
        migrations.AlterModelOptions(
            name='draft',
            options={'verbose_name_plural': 'drafts'},
        ),
        migrations.AlterModelOptions(
            name='sold',
            options={'verbose_name_plural': 'sold'},
        ),
    ]
