# Generated by Django 5.1.6 on 2025-03-23 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_deleted_options_alter_draft_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='image_url',
            field=models.ImageField(upload_to='holder/'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='image_url',
            field=models.ImageField(upload_to='holder/'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='image_url',
            field=models.ImageField(upload_to='holder/'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='image_url',
            field=models.ImageField(upload_to='holder/'),
        ),
    ]
