# Generated by Django 5.1.6 on 2025-03-24 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_alter_active_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='active',
            name='image_url',
            field=models.ImageField(upload_to='active'),
        ),
        migrations.AlterField(
            model_name='deleted',
            name='image_url',
            field=models.ImageField(upload_to='deleted'),
        ),
        migrations.AlterField(
            model_name='draft',
            name='image_url',
            field=models.ImageField(upload_to='draft'),
        ),
        migrations.AlterField(
            model_name='sold',
            name='image_url',
            field=models.ImageField(upload_to='sold'),
        ),
    ]
